# Generated by Django 4.1.1 on 2022-09-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.TextField(default='https://99px.ru/sstorage/56/2015/01/image_560401151755269388068.jpg', max_length=1000, verbose_name='Изображение'),
        ),
    ]
